name: MineResetLite
version: 0.4.5
main: com.koletar.jj.mineresetlite.MineResetLite
authors: [jjKoletar, VirtualByte, TWWSYesterday]
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core, PrisonMines, Multiworld]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.